# Generated by Django 5.0.1 on 2024-01-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image_1_product_image_2_product_image_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
