# Generated by Django 5.0.1 on 2024-01-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_5',
        ),
    ]
