# Generated by Django 5.0.1 on 2024-01-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
    ]
